<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP descripció del servidor... Escriu la paraula correctament si us plau';
$lang['pptpd_app_name'] = 'Servidor PPTP';
$lang['pptpd_dns_server'] = 'Servidor DNS';
$lang['pptpd_dns_server_invalid'] = 'El servidor DNS no es vàlid';
$lang['pptpd_internet_domain'] = 'Domini d\'Internet';
$lang['pptpd_internet_domain_invalid'] = 'El domini d\'Internet no es vàlid';
$lang['pptpd_ip_range_invalid'] = 'El rang de direcció IP no es vàlid';
$lang['pptpd_local_ip_range'] = 'Rang de IP local';
$lang['pptpd_pptp_server'] = 'Servidor PPTP';
$lang['pptpd_remote_ip_range'] = 'Rang de direccions IP remotes';
$lang['pptpd_wins_server'] = 'Servidor WINS';
$lang['pptpd_wins_server_invalid'] = 'El servidor WINS no es vàlid';
