<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP VPN allows users to connect to your network using a VPN client common to most operating systems.  PPTP is easy and useful for road warriors but is considered less secure than other technologies like OpenVPN.';
$lang['pptpd_app_name'] = 'Servidor PPTP';
$lang['pptpd_auto_configure_help'] = 'The PPTP server is currently in auto-configuration mode.  If you change your network settings, the PPTP server will intelligently make the necessary changes to its settings.  If you would like to disable auto-configuration, please click on the following button.';
$lang['pptpd_dns_server'] = 'Servidor DNS';
$lang['pptpd_dns_server_invalid'] = 'El servidor DNS no es vàlid';
$lang['pptpd_ip_range_invalid'] = 'El rang de direcció IP no es vàlid';
$lang['pptpd_local_ip_range'] = 'Rang de IP local';
$lang['pptpd_pptp_server'] = 'Servidor PPTP';
$lang['pptpd_remote_ip_range'] = 'Rang de direccions IP remotes';
$lang['pptpd_wins_server'] = 'Servidor WINS';
$lang['pptpd_wins_server_invalid'] = 'El servidor WINS no es vàlid';
