<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'Description du serveur PPTP... artisan des mots SVP.';
$lang['pptpd_app_name'] = 'Serveur PPTP';
$lang['pptpd_dns_server'] = 'Serveur DNS';
$lang['pptpd_dns_server_invalid'] = 'Le serveur DNS est invalide.';
$lang['pptpd_internet_domain'] = 'Domaine internet';
$lang['pptpd_internet_domain_invalid'] = 'Le domaine internet est invalide.';
$lang['pptpd_ip_range_invalid'] = 'La plage d\'IPs est invalide.';
$lang['pptpd_local_ip_range'] = 'Plage d\'IPs locales';
$lang['pptpd_pptp_server'] = 'Serveur PPTP';
$lang['pptpd_remote_ip_range'] = 'Plage d\'IPs distantes';
$lang['pptpd_wins_server'] = 'Serveur WINS';
$lang['pptpd_wins_server_invalid'] = 'Le serveur WINS est invalide.';
