<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP Server tanýmlamasý... wordsmith please.';
$lang['pptpd_app_name'] = 'PPTP Server';
$lang['pptpd_dns_server'] = 'DNS Server';
$lang['pptpd_dns_server_invalid'] = 'DNS server geçerli deðil.';
$lang['pptpd_internet_domain'] = 'Internet Domain';
$lang['pptpd_internet_domain_invalid'] = 'Internet domain geçerli deðil.';
$lang['pptpd_ip_range_invalid'] = 'IP aralýðý geçerli deðil.';
$lang['pptpd_local_ip_range'] = 'Yerel IP Aralýðý';
$lang['pptpd_pptp_server'] = 'PPTP Server';
$lang['pptpd_remote_ip_range'] = 'Uzak IP Aralýðý';
$lang['pptpd_wins_server'] = 'WINS Server';
$lang['pptpd_wins_server_invalid'] = 'WINS server geçerli deðil.';
