#!/bin/sh

TIMESTAMP=`date "+%b-%d-%Y-%T"`

# Set default configuration
#--------------------------

logger -p local6.notice -t installer "app-pptpd-core - setting default configuration"

if [ -e /etc/ppp/options.pptpd ]; then
    cp /etc/ppp/options.pptpd /var/clearos/pptpd/backup/options.pptpd.$TIMESTAMP
fi

cp /usr/clearos/apps/pptpd/deploy/options.pptpd /etc/ppp/options.pptpd

logger -p local6.notice -t installer "app-pptpd-core - setting default PAM configuration"

if [ -e /etc/pam.d/ppp ]; then
    cp /etc/pam.d/ppp /var/clearos/pptpd/backup/ppp.$TIMESTAMP
fi

cp /usr/clearos/apps/pptpd/deploy/ppp-pam /etc/pam.d/ppp

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-pptpd-core - enabling PPTP server"
chkconfig pptpd on >/dev/null 2>&1

logger -p local6.notice -t installer "app-pptpd-core - starting PPTP server"
service pptpd start >/dev/null 2>&1

if [ -x /etc/init.d/winbind ]; then
    logger -p local6.notice -t installer "app-pptpd-core - enabling Winbind server"
    chkconfig winbind on >/dev/null 2>&1

    logger -p local6.notice -t installer "app-pptpd-core - starting Winbind server"
    service winbind start >/dev/null 2>&1
fi

# Run auto-configuration
#-----------------------

/var/clearos/events/network_configuration/pptpd >/dev/null 2>&1
