<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP VPN allows users to connect to your network using a VPN client common to most operating systems.  PPTP is easy and useful for road warriors but is considered less secure than other technologies like OpenVPN.';
$lang['pptpd_app_name'] = 'PPTP Server';
$lang['pptpd_auto_configure_help'] = 'Der PPTP Server ist aktuell im Autokonfigurationsmodus.  Sollten Sie Ihre Netzwerkeinstellungen ändern wird der PPTP Server seine eigenen Einstellungen selbständig anpassen.  Wenn Sie den Autokonfigurationsmodus deaktivieren möchten klicken Sie auf den folgenden Button.';
$lang['pptpd_dns_server'] = 'DNS Server';
$lang['pptpd_dns_server_invalid'] = 'DNS Server ist ungültig.';
$lang['pptpd_ip_range_invalid'] = 'IP Adressbereich ist ungültig.';
$lang['pptpd_local_ip_range'] = 'Lokaler IP Adressbereich';
$lang['pptpd_pptp_server'] = 'PPTP Server';
$lang['pptpd_remote_ip_range'] = 'Externer IP Adressbereich';
$lang['pptpd_wins_server'] = 'WINS Server';
$lang['pptpd_wins_server_invalid'] = 'WINS Server ist ungültig.';
