<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP VPN allows users to connect to your network using a VPN client common to most operating systems.  PPTP is easy and useful for road warriors but is considered less secure than other technologies like OpenVPN.';
$lang['pptpd_app_name'] = 'PPTP Server';
$lang['pptpd_auto_configure_help'] = 'The PPTP server is currently in auto-configuration mode.  If you change your network settings, the PPTP server will intelligently make the necessary changes to its settings.  If you would like to disable auto-configuration, please click on the following button.';
$lang['pptpd_dns_server'] = 'DNS Server';
$lang['pptpd_dns_server_invalid'] = 'DNS Server ist ungültig.';
$lang['pptpd_ip_range_invalid'] = 'IP Adressbereich ist ungültig.';
$lang['pptpd_local_ip_range'] = 'Lokaler IP Adressbereich';
$lang['pptpd_pptp_server'] = 'PPTP Server';
$lang['pptpd_remote_ip_range'] = 'Externer IP Adressbereich';
$lang['pptpd_wins_server'] = 'WINS Server';
$lang['pptpd_wins_server_invalid'] = 'WINS Server ist ungültig.';
