<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP VPN allows users to connect to your network using a VPN client common to most operating systems.  PPTP is easy and useful for road warriors but is considered less secure than other technologies like OpenVPN.';
$lang['pptpd_app_name'] = 'Servidor PPTP';
$lang['pptpd_auto_configure_help'] = 'O Servidor PPTP está atualmente no modo auto-configuração. Se alterar suas configurações de rede, o servidor PPTP vai, inteligentemente, fazer as mudanças necessárias para as configurações. Se quiser desativar a auto-configuração, por favor, clique no botão seguinte.';
$lang['pptpd_dns_server'] = 'Servidor DNS';
$lang['pptpd_dns_server_invalid'] = 'Servidor DNS inválido.';
$lang['pptpd_ip_range_invalid'] = 'Faixa de IP inválida.';
$lang['pptpd_local_ip_range'] = 'Faixa de IP Local';
$lang['pptpd_pptp_server'] = 'Servidor PPTP';
$lang['pptpd_remote_ip_range'] = 'Faixa de IP Remoto';
$lang['pptpd_wins_server'] = 'Servidor WINS';
$lang['pptpd_wins_server_invalid'] = 'Servidor WINS inválido.';
