<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP Server description... wordsmith please.';
$lang['pptpd_app_name'] = 'PPTP 服务器';
$lang['pptpd_dns_server'] = 'DNS 服务器';
$lang['pptpd_dns_server_invalid'] = 'DNS server is invalid.';
$lang['pptpd_internet_domain'] = '互联网域名';
$lang['pptpd_internet_domain_invalid'] = 'Internet domain is invalid.';
$lang['pptpd_ip_range_invalid'] = 'IP range is invalid.';
$lang['pptpd_local_ip_range'] = '本地 IP 范围';
$lang['pptpd_pptp_server'] = 'PPTP 服务器';
$lang['pptpd_remote_ip_range'] = '远程 IP 范围';
$lang['pptpd_wins_server'] = 'WINS Server';
$lang['pptpd_wins_server_invalid'] = 'WINS server is invalid.';
