<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'Beskrivning av PPTP-server.';
$lang['pptpd_app_name'] = 'PPTP-server';
$lang['pptpd_dns_server'] = 'DNS-server';
$lang['pptpd_dns_server_invalid'] = 'DNS-servern är ogiltig.';
$lang['pptpd_internet_domain'] = 'Internetdomän';
$lang['pptpd_internet_domain_invalid'] = 'Internetdomänen är ogiltig.';
$lang['pptpd_ip_range_invalid'] = 'IP-området är ogiltigt.';
$lang['pptpd_local_ip_range'] = 'Lokalt IP-område';
$lang['pptpd_pptp_server'] = 'PPTP-server';
$lang['pptpd_remote_ip_range'] = 'Fjärrdatorns IP-område';
$lang['pptpd_wins_server'] = 'WINS-server';
$lang['pptpd_wins_server_invalid'] = 'WINS-servern är ogiltig.';
