<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP Server description... wordsmith please.';
$lang['pptpd_app_name'] = 'PPTP Server';
$lang['pptpd_dns_server'] = 'DNS Server';
$lang['pptpd_dns_server_invalid'] = 'DNS server is invalid.';
$lang['pptpd_internet_domain'] = 'Internet Domain';
$lang['pptpd_internet_domain_invalid'] = 'Internet domain is invalid.';
$lang['pptpd_ip_range_invalid'] = 'IP range is invalid.';
$lang['pptpd_local_ip_range'] = 'Local IP Range';
$lang['pptpd_pptp_server'] = 'PPTP Server';
$lang['pptpd_remote_ip_range'] = 'Remote IP Range';
$lang['pptpd_wins_server'] = 'WINS Server';
$lang['pptpd_wins_server_invalid'] = 'WINS server is invalid.';
