<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'PPTP server';
$lang['pptpd_app_name'] = 'PPTP Server';
$lang['pptpd_dns_server'] = 'DNS server';
$lang['pptpd_dns_server_invalid'] = 'Ongeldige DNS server';
$lang['pptpd_internet_domain'] = 'Internet domein ';
$lang['pptpd_internet_domain_invalid'] = 'Ongeldig internet domain';
$lang['pptpd_ip_range_invalid'] = 'Ongeldige IP reeks';
$lang['pptpd_local_ip_range'] = 'Lokale IP reeks';
$lang['pptpd_pptp_server'] = 'PPTP Server';
$lang['pptpd_remote_ip_range'] = 'Externe IP reeks';
$lang['pptpd_wins_server'] = 'WINS server';
$lang['pptpd_wins_server_invalid'] = 'Ongeldige WINS server';
