<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['pptpd_app_description'] = 'Tu będzie opis serwera PPTP.';
$lang['pptpd_app_name'] = 'Serwer PPTP';
$lang['pptpd_dns_server'] = 'Serwer DNS';
$lang['pptpd_dns_server_invalid'] = 'Podany serwer DNS jest nieprawidłowy.';
$lang['pptpd_internet_domain'] = 'Domena internetowa';
$lang['pptpd_internet_domain_invalid'] = 'Podana domena internetowa jest nieprawidłowa.';
$lang['pptpd_ip_range_invalid'] = 'Podany zakres adresów IP jest nieprawidłowy.';
$lang['pptpd_local_ip_range'] = 'Zakres lokalnych adresów IP';
$lang['pptpd_pptp_server'] = 'Serwer PPTP';
$lang['pptpd_remote_ip_range'] = 'Zakres zdalnych adresów IP';
$lang['pptpd_wins_server'] = 'Serwer WINS';
$lang['pptpd_wins_server_invalid'] = 'Podany serwer WINS jest nieprawidłowy.';
